package com.task.ecommerce.payment.dto;

import com.task.ecommerce.payment.dto.User;
import lombok.Data;

import java.util.List;
import java.util.Map;

@Data
public class Profile {

    private Long id;
    private User user;
    private String createdAt;
    private Boolean active;
    private String profileType;
    private List<String> phones;
    private List<String> companyEmails;
    private String companyName;
    private String state;
    private String country;
    private String city;
    private String postalCode;
    private String street;
    private Boolean emailNotification;
    private String orderRetrievalEndpoint;
    private String deliveryUpdateEndpoint;
    private String logoUrl;
    private Boolean isMobadra;
    private String sector;
    private Boolean is2faEnabled;
    private String otpSentTo;
    private Integer activationMethod;
    private String signedUpThrough;
    private Integer failedAttempts;
    private List<Object> customExportColumns;
    private List<Object> serverIP;
    private String username;
    private String primaryPhoneNumber;
    private Boolean primaryPhoneVerified;
    private Boolean isTempPassword;
    private String otp2faSentAt;
    private Integer otp2faAttempt;
    private String otpSentAt;
    private String otpValidatedAt;
    private String awbBanner;
    private String emailBanner;
    private String identificationNumber;
    private String deliveryStatusCallback;
    private String merchantExternalLink;
    private String merchantStatus;
    private Boolean deactivatedByBank;
    private String bankDeactivationReason;
    private String bankMerchantStatus;
    private String nationalId;
    private String superAgent;
    private String walletLimitProfile;
    private String address;
    private String commercialRegistration;
    private String commercialRegistrationArea;
    private String distributorCode;
    private String distributorBranchCode;
    private Boolean allowTerminalOrderId;
    private Boolean allowEncryptionBypass;
    private String walletPhoneNumber;
    private Boolean suspicious;
    private Double latitude;
    private Double longitude;
    private Map<String, Object> bankStaffs;
    private String bankRejectionReason;
    private Boolean bankReceivedDocuments;
    private String bankMerchantDigitalStatus;
    private String bankDigitalRejectionReason;
    private Boolean filledBusinessData;
    private String dayStartTime;
    private String dayEndTime;
    private Boolean withholdTransfers;
    private Boolean manualSettlement;
    private String smsSenderName;
    private String withholdTransfersReason;
    private String withholdTransfersNotes;
    private Boolean canBillDepositWithCard;
    private Boolean canTopupMerchants;
    private String topupTransferId;
    private Boolean referralEligible;
    private Boolean isEligibleToBeRanger;
    private Boolean isRanger;
    private Boolean isPoaching;
    private Boolean paymobAppMerchant;
    private String settlementFrequency;
    private String dayOfTheWeek;
    private String dayOfTheMonth;
    private Boolean allowTransactionNotifications;
    private Boolean allowTransferNotifications;
    private String sallefnyAmountWhole;
    private String sallefnyFeesWhole;
    private String paymobAppFirstLogin;
    private String paymobAppLastActivity;
    private Boolean payoutEnabled;
    private Boolean payoutTerms;
    private Boolean isBillsNew;
    private Boolean canProcessMultipleRefunds;
    private Boolean settlementClassification;
    private Boolean instantSettlementEnabled;
    private Boolean instantSettlementTransactionOtpVerified;
    private String preferredLanguage;
    private Boolean ignoreFlashCallbacks;
    private String acqPartner;
    private String dom;
    private String bankRelated;
    private List<Object> permissions;
}